from .estado import Estado
from .fim_de_jogo import FimDeJogo
from .menu_creditos import MenuCreditos
from .menu_opcoes import MenuOpcoes
from .menu_pausa import MenuPausa
from .menu_principal import MenuPrincipal
from .menu_ranking import MenuRanking
from .menu_registro import MenuRegistro
from .menu_vitoria import MenuVitoria
from .partida import Partida
